### ISSUE TITLE
Typo in bash script variable name

### ISSUE THREAD

**Issue by rollwagen** [tradichel/SecurityMetricsAutomation#1]
Thanks for making this repo available. 

Looks like there’s a “v” too many. 

https://github.com/tradichel/SecurityMetricsAutomation/blob/97b56cb35458c376873f5f380727845266ef78b7/IAM/stacks/User/user_functions.sh#L17

Cheers, Markus

**Comment by tradichel** [comment]
Thank you. Sorry it took me so long to respond!
